"""
End-to-end tests for `discrete_modulus.certificate_builder`: solver trace
(+ original graph) -> certificate, on the two real example graphs
`Certification_Plan.md` §7 names as the "definition of done" targets.

`cpp/examples/{house,nested}.trace.json` are static, checked-in traces
(`spt_mod <prefix> --trace`'s own output, generated once and committed --
the same convention `house.eta` already uses), not regenerated by these
tests -- keeps this suite independent of the C++ build, matching
`test.yml`'s own python-only CI scope.

`house` is the single-round case (no deflation needed, per
`Certification_Plan.md` §5.1's own house-graph walkthrough); `nested`
exercises real multi-round gluing across 3 rounds, the middle one with
genuine parallel edges once shrunk (`scratch/nested_trace_validation.py`
found multiplicity up to 3), the third requiring within-round core
deflation (`Certification_Plan.md` §5.1.5's K20-shaped example).
"""

from __future__ import annotations

import json
from pathlib import Path

import jsonschema
import pytest

from discrete_modulus.certificate_builder import (
    build_certificate,
    load_edge_list,
    parse_solver_trace,
    validate_certificate,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
EXAMPLES = REPO_ROOT / "cpp" / "examples"
SCHEMA_PATH = REPO_ROOT / "scratch" / "certificate_schema.json"


def _build(name: str) -> dict:
    g = load_edge_list(str(EXAMPLES / f"{name}.edges"))
    with open(EXAMPLES / f"{name}.trace.json") as f:
        trace = parse_solver_trace(json.load(f))
    return build_certificate(g, trace)


@pytest.fixture(scope="module")
def schema() -> dict:
    with open(SCHEMA_PATH) as f:
        return json.load(f)


@pytest.mark.parametrize("name", ["house", "nested"])
def test_certificate_matches_schema(name: str, schema: dict) -> None:
    cert = _build(name)
    jsonschema.Draft202012Validator.check_schema(schema)
    jsonschema.validate(cert, schema)


@pytest.mark.parametrize("name", ["house", "nested"])
def test_certificate_passes_its_own_validation(name: str) -> None:
    validate_certificate(_build(name))


def test_house_deflates_into_its_known_core_plus_remainder() -> None:
    # House is a single round (the whole graph is dispatched at once,
    # Certification_Plan.md §5.1), but within that round core_deflation
    # still finds one core (the chord triangle -- the same one
    # test_core_deflation.py / test_pmf_construction.py already exercise),
    # so it deflates into 2 pieces, not 1 -- each strictly homogeneous, each
    # with a uniform 3-tree/weight-1/3 local pmf (theta = 2/3 = (3-1)/3 on
    # a 3-edge triangle-shaped piece).
    cert = _build("house")
    assert len(cert["pieces"]) == 2
    for piece in cert["pieces"]:
        assert len(piece["edges"]) == 3
        trees = piece["local_pmf"]["trees"]
        assert len(trees) == 3
        for t in trees:
            assert t["weight"] == [1, 3]
    covered = {e for piece in cert["pieces"] for e in piece["edges"]}
    assert covered == set(range(6))


def test_house_matches_the_recorded_eta() -> None:
    # cpp/examples/house.eta is spt_mod's own golden output: every edge
    # gets eta* = 2/3. Cross-checking the certificate's own pieces against
    # it (by recomputing each edge's marginal from the certificate alone,
    # with no access to FactoredPmf) is an independent confirmation that
    # nothing was lost/miscounted in the local-to-global index translation.
    from fractions import Fraction

    cert = _build("house")
    m = len(cert["graph"]["edges"])
    marginal = [Fraction(0)] * m
    for piece in cert["pieces"]:
        for t in piece["local_pmf"]["trees"]:
            w = Fraction(*t["weight"])
            for e in t["edges"]:
                marginal[e] += w

    edge_index = {frozenset(e): i for i, e in enumerate(cert["graph"]["edges"])}
    with open(EXAMPLES / "house.eta") as f:
        for line in f:
            a, b, p, q = line.split()
            i = edge_index[frozenset((int(a), int(b)))]
            assert marginal[i] == Fraction(int(p), int(q))


def test_nested_has_three_rounds_worth_of_pieces() -> None:
    # Round 2 (the K20-shaped piece, |C|=190) is the one Certification_Plan.md
    # §5.1.5 documents as needing core deflation -- so nested should produce
    # more pieces than rounds.
    cert = _build("nested")
    with open(EXAMPLES / "nested.trace.json") as f:
        trace_data = json.load(f)
    assert len(trace_data["rounds"]) == 3
    assert len(cert["pieces"]) >= 3
